#!/bin/zsh

# asumes zsh and java is installed (openjdk-11-jdk works)
# download antlr-4.13.1-complete.jar from https://github.com/antlr/website-antlr4/tree/gh-pages/download and put in /usr/local/lib/
# change directory to this folder and run ./generate.sh
rm -r autogenerated/*.cc
antlr4 -v 4.13.1 -Dlanguage=Cpp GQLLexer.g4 -o autogenerated -no-listener -visitor
antlr4 -v 4.13.1  -Dlanguage=Cpp GQLParser.g4 -o autogenerated -no-listener -visitor
autoload zmv
zmv 'autogenerated/(*).cpp' autogenerated/'$1.cc'
