
rm -r autogenerated/*.cpp
rm -r autogenerated/*.cc
#find . -wholename "autogenerated/*.cpp" -type f -delete

#java -Xmx500M -cp "/usr/local/lib/antlr-4.9.3-complete.jar:$CLASSPATH" org.antlr.v4.Tool -Dlanguage=Cpp SparqlLexer.g4 -o autogenerated -no-listener -visitor
#java -Xmx500M -cp "/usr/local/lib/antlr-4.9.3-complete.jar:$CLASSPATH" org.antlr.v4.Tool -Dlanguage=Cpp SparqlParser.g4 -o autogenerated -no-listener -visitor
antlr4 -Dlanguage=Cpp SparqlLexer.g4 -o autogenerated -no-listener -visitor
antlr4 -Dlanguage=Cpp SparqlParser.g4 -o autogenerated -no-listener -visitor
##autoload zmv
rename 's/cpp$/cc/' autogenerated/*.cpp
#cp 'autogenerated/(*).cpp' autogenerated/'$1.cc'
